name: uMessagebox
description: Simple mootools modal messagebox
author: joseluis_q
category: Interface
tags: [modalbox, messagebox, popup, ui]
current: 1.1
license: MIT License
demo: http://goo.gl/14y2S